/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#35260c",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c5c6cd",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ddc39d",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed": "#fadfb8",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "surface-tint": "#545f73",
        "on-error": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#111c2d",
        "background": "#f7f9fb",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "primary-fixed-dim": "#bcc7de",
        "primary-fixed": "#d8e3fb",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed": "#271902",
        "on-surface-variant": "#45474c",
        "inverse-surface": "#2d3133",
        "primary-container": "#1e293b",
        "on-secondary-container": "#fffbff",
        "secondary-container": "#8455ef",
        "on-secondary-fixed-variant": "#5516be",
        "on-background": "#191c1e",
        "secondary": "#6b38d4",
        "on-secondary-fixed": "#23005c",
        "outline": "#75777d",
        "on-tertiary-fixed-variant": "#564427",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#3c475a",
        "on-secondary": "#ffffff",
        "on-primary-container": "#8590a6",
        "secondary-fixed": "#e9ddff",
        "on-tertiary-container": "#a38c6a",
        "inverse-primary": "#bcc7de",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed-dim": "#d0bcff",
        "tertiary": "#1e1200",
        "primary": "#091426",
        "muted": "#8590a6",
        "card": "#ffffff",
        "warning": "#f59e0b",
        "success": "#22c55e",
      },
    },
  },
  plugins: [],
}
